use_frameworks!
platform :ios, '10.0'

target 'AHTopTabBarViewController_Example' do
  pod 'AHTopTabBarViewController', :path => '../'

  target 'AHTopTabBarViewController_Tests' do
    inherit! :search_paths

    
  end
end
